---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    run_list:
      - recipe[golden_cobra::default]
    attributes:
